In [487]:
import pandas as pd
from random import random
import time

In [136]:
# load model
from sklearn.externals import joblib

clf = joblib.load('../02 Individual Match Prediction/match_prediction_model.pkl')

In [340]:
grpA = ["Russia", "Uruguay", "Egypt", "Saudi Arabia"]
grpB = ["Spain", "Portugal", "Iran", "Morocco"]
grpC = ["France", "Denmark", "Australia", "Peru"]
grpD = ["Croatia", "Nigeria", "Iceland", "Argentina"]
grpE = ["Brazil", "Switzerland", "Serbia", "Costa Rica"]
grpF = ["Mexico", "Germany", "Sweden", "South Korea"]
grpG = ["Belgium", "England", "Panama", "Tunisia"]
grpH = ["Japan", "Senegal", "Poland", "Colombia"]

In [20]:
world_cup_df = pd.read_csv("../01 Data Collection/data/final/full_2018.csv")

In [21]:
world_cup_df = world_cup_df.drop(['Date', 'Team1_score', 'Team2_score', 'team1_fouls',
       'team2_fouls', 'team1_yellow_cards', 'team2_yellow_cards',
       'team1_red_cards', 'team2_red_cards', 'team1_offsides',
       'team2_offsides', 'team1_won_corners', 'team2_won_corners',
       'team1_saves', 'team2_saves', 'team1_possession', 'team2_possession',
       'team1_shots', 'team2_shots','team1_lineup', 'team2_lineup'], axis = 1)

In [22]:
world_cup_df

Team1         Team2  team1_avg_wins  team1_avg_draws  team1_avg_gd  \
0        Russia  Saudi Arabia             0.0              0.4          -1.2   
1         Egypt       Uruguay             0.0              0.4          -1.0   
2       Morocco          Iran             0.8              0.2           1.2   
3      Portugal         Spain             0.4              0.4           0.2   
4        France     Australia             0.6              0.2           1.0   
5     Argentina       Iceland             0.6              0.0           0.0   
6          Peru       Denmark             0.8              0.2           1.8   
7       Croatia       Nigeria             0.4              0.2          -0.4   
8    Costa Rica        Serbia             0.4              0.0          -0.4   
9       Germany        Mexico             0.2              0.4          -0.2   
10       Brazil   Switzerland             0.8              0.2           1.8   
11       Sweden   South Korea             0.2              0.4          -0.2   
12      Belgium        Panama             0.8              0.2           2.2   
13      Tunisia       England             0.4              0.4           0.2   
14     Colombia         Japan             0.4              0.4           0.8   
15       Poland       Senegal             0.4              0.2           0.6   
16       Russia         Egypt             0.2              0.2          -0.2   
17     Portugal       Morocco             0.2              0.6           0.0   
18      Uruguay  Saudi Arabia             0.8              0.0           1.2   
19         Iran         Spain             0.8              0.0           0.6   
20      Denmark     Australia             0.6              0.4           0.8   
21       France          Peru             0.8              0.2           1.4   
22    Argentina       Croatia             0.4              0.2          -0.2   
23       Brazil    Costa Rica             0.8              0.2           1.8   
24      Nigeria       Iceland             0.0              0.2          -1.2   
25       Serbia   Switzerland             0.6              0.0           1.0   
26      Belgium       Tunisia             0.8              0.2           2.6   
27  South Korea        Mexico             0.2              0.2          -0.6   
28      Germany        Sweden             0.2              0.2          -0.4   
29      England        Panama             0.8              0.2           1.0   

    team2_avg_wins  team2_avg_draws  team2_avg_gd  avg_age_t1  avg_gpa_t1  \
0              0.4              0.0          -0.2    0.000000    0.000000   
1              0.6              0.2           1.0   28.000000    0.063885   
2              0.6              0.0           0.2   27.166667    0.101380   
3              0.4              0.6           1.2   27.333333    0.074083   
4              0.6              0.2           0.8   24.250000    0.107216   
5              0.2              0.2          -0.6   29.500000    0.096890   
6              0.4              0.4           0.4   29.000000    0.075670   
7              0.2              0.2          -0.6   28.250000    0.122674   
8              0.4              0.2           0.8   28.428571    0.083375   
9              0.4              0.2           0.2   26.500000    0.162741   
10             0.6              0.4           1.8   28.285714    0.183033   
11             0.2              0.2          -0.6   28.250000    0.084396   
12             0.2              0.2          -1.4   27.428571    0.113604   
13             0.6              0.4           0.8   25.714286    0.098889   
14             0.2              0.2          -0.6   26.125000    0.072649   
15             0.2              0.6           0.2   28.857143    0.122883   
16             0.0              0.4          -1.0    0.000000    0.000000   
17             0.6              0.2           0.8   27.555556    0.066042   
18             0.2              0.0          -1.6   28.833333    0

In [185]:
# scraper didnt work for colombia
# colombia_feats = ["Colombia",0.4,0.4,0.8,27.181818,0.172363,0.076749,0.136069,26204]
# country_feature_df = country_feature_df.append(colombia_s, ignore_index=True)
# country_feature_df.to_csv("country_features_2018.csv",index=False)

In [24]:
# for each team, go through the dataframe and retrieve the first row that it appears in and extract the features
all_countries = grpA + grpB + grpC + grpD + grpE + grpF + grpG + grpH

In [26]:
team = all_countries[0]

In [50]:
matches_df = world_cup_df.loc[(world_cup_df.Team1 == team) | (world_cup_df.Team2 == team)]
matches_df = matches_df.reset_index(drop=True)
first_match = matches_df.iloc[0]
get_features(first_match_team)

In [81]:
def get_features(first_match, team):
    if first_match.Team1 == team:
        cols = list(filter(lambda x: "1" in x,list(first_match.keys())))
        return list(first_match[cols])
    cols = list(filter(lambda x: "2" in x,list(first_match.keys())))
    return list(first_match[cols])

In [82]:
all_features = []
for team in all_countries:
    try:
        matches_df = world_cup_df.loc[(world_cup_df.Team1 == team) | (world_cup_df.Team2 == team)]
        matches_df = matches_df.reset_index(drop=True)
        first_match = matches_df.iloc[0]
        if get_features(first_match, team) == None:
            print(team)
        all_features.append(get_features(first_match,team))
    except:
        continue

In [88]:
header = ['name','avg_wins','avg_draws', 'avg_gd', 'avg_age',
       'avg_gpa', 'avg_apa', 'avg_ycpa', 'total_minutes']
country_feature_df = pd.DataFrame(all_features, columns=header)

In [334]:
# given two countries, get probabilities
def get_probabilities(team1, team2, country_feature_df,clf):
    team1_feats = country_feature_df[country_feature_df.name == team1].drop("name",axis=1).values.tolist()[0]
    team2_feats = country_feature_df[country_feature_df.name == team2].drop("name",axis=1).values.tolist()[0]
    proba = clf.predict_proba(np.array(team1_feats+team2_feats).reshape(1, -1))
#     print(team1+"_wins",team2+"_wins","draw")
#     print(proba)
    return proba

In [201]:
proba = get_probabilities("Poland", "Colombia", country_feature_df,clf)

Poland_wins Colombia_wins draw
[[ 0.3299934   0.32814048  0.34186612]]


In [247]:
test = ["A","B","C","D"]

## Simulating the tournament

In [253]:
# round robin
def generate_matches(group):
    group = group.copy()
    games = []
    for team in group.copy():
        group.remove(team)
        for team2 in group:
            games.append((team,team2))
    return games

In [255]:
test = generate_matches(grpA)

In [365]:
def get_simulated_result(proba):
    dist = proba.round(decimals=2) * 100
    pool = []
    counter = 0
    for p in dist[0]:
        temp = [counter] * int(p) 
        pool += temp
        counter += 1
    try:
        result = pool[int(random() * 100)]
    except:
        result = pool[-1]
    return result

In [338]:
def generate_standings(grp):
    standings = {x: [0,0,0] for x in grp}
    return standings

In [347]:
def get_simulated_standings(matches_list, grp):
    standings = generate_standings(grp)
    for match in matches_list:
        proba = get_probabilities(match[0], match[1],country_feature_df,clf)
        result = get_simulated_result(proba)
        if result == 0:
            standings[match[0]][0] += 1
            standings[match[1]][1] += 1
        elif result == 1:
            standings[match[0]][1] += 1
            standings[match[1]][0] += 1
        else:
            standings[match[0]][2] += 1
            standings[match[1]][2] += 1
    return standings

In [322]:
stand = get_simulated_standings(generate_matches(grpA),grpA)

Russia_wins Uruguay_wins draw
[[ 0.24447853  0.4647304   0.29079107]]
Russia_wins Egypt_wins draw
[[ 0.34564781  0.37343658  0.28091561]]
Russia_wins Saudi Arabia_wins draw
[[ 0.3485933   0.33599291  0.31541379]]
Uruguay_wins Egypt_wins draw
[[ 0.41106128  0.25523278  0.33370594]]
Uruguay_wins Saudi Arabia_wins draw
[[ 0.42700185  0.20265341  0.37034474]]
Egypt_wins Saudi Arabia_wins draw
[[ 0.37005237  0.28047353  0.3494741 ]]


In [323]:
stand

{'Egypt': [2, 1, 0],
 'Russia': [1, 2, 0],
 'Saudi Arabia': [1, 2, 0],
 'Uruguay': [2, 1, 0]}

In [502]:
def get_top_two(standings, grp):
    first = None
    first_score = 0
    second = None
    second_score = 0
    for team in grp:
        wld = standings[team]
        score = 3 * wld[0] + 1 * wld[2]
        if score > first_score:
            second = first
            second_score = first_score
            first = team
            first_score = score
        elif score > second_score:
            second = team
            second_score = score
    return (first,second)

In [327]:
get_top_two(stand, grpA)

('Uruguay', 'Egypt')

In [342]:
wc_groups = [grpA, grpB, grpC, grpD, grpE, grpF, grpG, grpH]

In [472]:
def round_robin(wc_groups):
    ro16 = []
    for grp in wc_groups:
        matches = generate_matches(grp)
        standings = get_simulated_standings(matches,grp)
        ro16.append(get_top_two(standings,grp))
    return ro16

In [368]:
ro16 = round_robin(wc_groups)

['Russia', 'Uruguay', 'Egypt', 'Saudi Arabia']
{'Egypt': [1, 1, 1], 'Uruguay': [0, 1, 2], 'Saudi Arabia': [1, 0, 2], 'Russia': [1, 1, 1]}
['Spain', 'Portugal', 'Iran', 'Morocco']
{'Morocco': [2, 0, 1], 'Portugal': [1, 0, 2], 'Iran': [0, 3, 0], 'Spain': [1, 1, 1]}
['France', 'Denmark', 'Australia', 'Peru']
{'Denmark': [1, 1, 1], 'Peru': [0, 2, 1], 'France': [2, 1, 0], 'Australia': [2, 1, 0]}
['Croatia', 'Nigeria', 'Iceland', 'Argentina']
{'Nigeria': [1, 2, 0], 'Argentina': [2, 0, 1], 'Iceland': [2, 0, 1], 'Croatia': [0, 3, 0]}
['Brazil', 'Switzerland', 'Serbia', 'Costa Rica']
{'Serbia': [2, 1, 0], 'Switzerland': [1, 2, 0], 'Brazil': [2, 1, 0], 'Costa Rica': [1, 2, 0]}
['Mexico', 'Germany', 'Sweden', 'South Korea']
{'Sweden': [1, 0, 2], 'South Korea': [0, 2, 1], 'Mexico': [0, 1, 2], 'Germany': [2, 0, 1]}
['Belgium', 'England', 'Panama', 'Tunisia']
{'Panama': [0, 2, 1], 'Tunisia': [0, 0, 3], 'England': [2, 0, 1], 'Belgium': [1, 1, 1]}
['Japan', 'Senegal', 'Poland', 'Colombia']
{'Japan': [

In [396]:
ro16

[('Saudi Arabia', 'Russia'),
 ('Morocco', 'Portugal'),
 ('France', 'Australia'),
 ('Iceland', 'Argentina'),
 ('Brazil', 'Serbia'),
 ('Germany', 'Sweden'),
 ('England', 'Belgium'),
 ('Poland', 'Colombia')]

In [372]:
ro16[1][1]

'Portugal'

In [375]:
def get_simulated_result_playoffs(proba, team1, team2):
    result = get_simulated_result(proba)
    while result == 2:
        result = get_simulated_result(proba)
    if result == 0:
        return team1
    return team2

In [397]:
# Round of 16
def ro16_sim(ro16):
    ro8 = []
    match1_proba = get_probabilities(ro16[0][0], ro16[1][1], country_feature_df, clf)
    ro8.append(get_simulated_result_playoffs(match1_proba,ro16[0][0], ro16[1][1]))
    
    match2_proba = get_probabilities(ro16[2][0], ro16[3][1], country_feature_df, clf)
    ro8.append(get_simulated_result_playoffs(match2_proba,ro16[2][0], ro16[3][1]))
    
    match3_proba = get_probabilities(ro16[4][0], ro16[5][1], country_feature_df, clf)
    ro8.append(get_simulated_result_playoffs(match3_proba,ro16[4][0], ro16[5][1])) 
    
    match4_proba = get_probabilities(ro16[6][0], ro16[7][1], country_feature_df, clf)
    ro8.append(get_simulated_result_playoffs(match4_proba,ro16[6][0], ro16[7][1]))    
    
    match5_proba = get_probabilities(ro16[1][0], ro16[0][1], country_feature_df, clf)
    ro8.append(get_simulated_result_playoffs(match5_proba,ro16[1][0], ro16[0][1]))
    
    match6_proba = get_probabilities(ro16[3][0], ro16[2][1], country_feature_df, clf)
    ro8.append(get_simulated_result_playoffs(match6_proba,ro16[3][0], ro16[2][1]))
    
    match7_proba = get_probabilities(ro16[5][0], ro16[4][1], country_feature_df, clf)
    ro8.append(get_simulated_result_playoffs(match7_proba,ro16[5][0], ro16[4][1]))
    
    match8_proba = get_probabilities(ro16[7][0], ro16[6][1], country_feature_df, clf)
    ro8.append(get_simulated_result_playoffs(match8_proba,ro16[7][0], ro16[6][1]))
    return ro8
    

In [398]:
ro8 = ro16_sim(ro16)

In [399]:
ro8

['Saudi Arabia',
 'France',
 'Sweden',
 'England',
 'Russia',
 'Australia',
 'Germany',
 'Belgium']

In [401]:
def ro8_sim(ro8):
    ro4 = []
    match1_proba = get_probabilities(ro8[0], ro8[1], country_feature_df, clf)
    ro4.append(get_simulated_result_playoffs(match1_proba,ro8[0], ro8[1]))
    match2_proba = get_probabilities(ro8[2], ro8[3], country_feature_df, clf)
    ro4.append(get_simulated_result_playoffs(match2_proba,ro8[2], ro8[3]))    
    match3_proba = get_probabilities(ro8[4], ro8[5], country_feature_df, clf)
    ro4.append(get_simulated_result_playoffs(match3_proba,ro8[4], ro8[5]))
    match4_proba = get_probabilities(ro8[6], ro8[7], country_feature_df, clf)
    ro4.append(get_simulated_result_playoffs(match4_proba,ro8[6], ro8[7]))    
    return ro4

In [416]:
ro4 = ro8_sim(ro8)

In [437]:
ro4

['France', 'England', 'Australia', 'Belgium']

In [418]:
def ro4_sim(ro4):
    third_place = ro4.copy()
    ro2 = []
    match1_proba = get_probabilities(ro4[0], ro4[1], country_feature_df, clf)
    result1 = get_simulated_result_playoffs(match1_proba,ro4[0], ro4[1])
    ro2.append(result1)
    match2_proba = get_probabilities(ro4[2], ro4[3], country_feature_df, clf)
    result2 = get_simulated_result_playoffs(match1_proba,ro4[2], ro4[3])
    ro2.append(result2)
    third_place.remove(result1)
    third_place.remove(result2)
    return ro2, third_place

In [438]:
finals, third_playoff = ro4_sim(ro4)

In [439]:
finals

['France', 'Australia']

In [440]:
third_playoff

['England', 'Belgium']

In [441]:
#finals
finals_proba = get_probabilities(finals[0], finals[1], country_feature_df, clf)
first = get_simulated_result_playoffs(finals_proba,finals[0], finals[1])
finals.remove(first)
second = finals[0]

In [442]:
print(first,second)

Australia France


In [443]:
third_proba = get_probabilities(third_playoff[0], third_playoff[1], country_feature_df, clf)
third = get_simulated_result_playoffs(third_proba,third_playoff[0], third_playoff[1])

In [444]:
third

'Belgium'

Now, repeat for 10000 times...

In [491]:
def world_cup_sim(wc_groups):
    ro16 = round_robin(wc_groups)
    ro8 = ro16_sim(ro16)
    ro4 = ro8_sim(ro8)
    finals, third_playoff = ro4_sim(ro4)
    # finals
    finals_proba = get_probabilities(finals[0], finals[1], country_feature_df, clf)
    first = get_simulated_result_playoffs(finals_proba,finals[0], finals[1])
    finals.remove(first)
    second = finals[0]
    # third_playoff
    third_proba = get_probabilities(third_playoff[0], third_playoff[1], country_feature_df, clf)
    third = get_simulated_result_playoffs(third_proba,third_playoff[0], third_playoff[1])
    third_playoff.remove(third)
    fourth = finals[0]
    return first, second, third, fourth

In [469]:
world_cup_sim(wc_groups)

['Russia', 'Uruguay', 'Egypt', 'Saudi Arabia']
{'Egypt': [1, 0, 2], 'Uruguay': [0, 1, 2], 'Saudi Arabia': [0, 0, 3], 'Russia': [0, 0, 3]}
['Spain', 'Portugal', 'Iran', 'Morocco']
{'Morocco': [1, 2, 0], 'Portugal': [2, 1, 0], 'Iran': [1, 2, 0], 'Spain': [2, 1, 0]}
['France', 'Denmark', 'Australia', 'Peru']
{'Denmark': [0, 0, 3], 'Peru': [1, 0, 2], 'France': [0, 1, 2], 'Australia': [0, 0, 3]}
['Croatia', 'Nigeria', 'Iceland', 'Argentina']
{'Nigeria': [1, 1, 1], 'Argentina': [0, 3, 0], 'Iceland': [2, 0, 1], 'Croatia': [2, 1, 0]}
['Brazil', 'Switzerland', 'Serbia', 'Costa Rica']
{'Serbia': [0, 1, 2], 'Switzerland': [0, 2, 1], 'Brazil': [1, 0, 2], 'Costa Rica': [2, 0, 1]}
['Mexico', 'Germany', 'Sweden', 'South Korea']
{'Sweden': [2, 0, 1], 'South Korea': [0, 3, 0], 'Mexico': [1, 1, 1], 'Germany': [2, 1, 0]}
['Belgium', 'England', 'Panama', 'Tunisia']
{'Panama': [1, 2, 0], 'Tunisia': [1, 1, 1], 'England': [1, 1, 1], 'Belgium': [2, 1, 0]}
['Japan', 'Senegal', 'Poland', 'Colombia']
{'Japan': [

('Brazil', 'Egypt', 'Denmark')

In [508]:
sim_results = {"first":[],"second":[],"third":[], "fourth":[]}
for i in range(1000):
    first, second, third, fourth = world_cup_sim(wc_groups)
    sim_results["first"].append(first)
    sim_results["second"].append(second)
    sim_results["third"].append(third)
    sim_results["fourth"].append(fourth)

In [509]:
from collections import Counter
Counter(sim_results["first"]).most_common()[:5]

[('Brazil', 172),
 ('Belgium', 104),
 ('Peru', 103),
 ('Uruguay', 56),
 ('Portugal', 53)]

In [510]:
Counter(sim_results["second"]).most_common()[:5]

[('Brazil', 63),
 ('Belgium', 59),
 ('Peru', 53),
 ('Poland', 50),
 ('England', 48)]

In [511]:
Counter(sim_results["third"]).most_common()[:5]

[('Brazil', 110),
 ('Belgium', 84),
 ('Peru', 62),
 ('Portugal', 53),
 ('Uruguay', 52)]

In [512]:
Counter(sim_results["fourth"]).most_common()[:5]

[('Brazil', 63),
 ('Belgium', 59),
 ('Peru', 53),
 ('Poland', 50),
 ('England', 48)]

* First: Brazil
* Second: Belgium
* Third: Peru
* Fourth: Poland
* Finals

In [526]:
sim_results = {"first":[],"second":[],"third":[], "fourth":[]}
for i in range(100000):
    first, second, third, fourth = world_cup_sim(wc_groups)
    sim_results["first"].append(first)
    sim_results["second"].append(second)
    sim_results["third"].append(third)
    sim_results["fourth"].append(fourth)

KeyboardInterrupt: 

In [527]:
from collections import Counter
Counter(sim_results["first"]).most_common()[:5]

[('Brazil', 10946),
 ('Belgium', 6396),
 ('Peru', 6292),
 ('Portugal', 2765),
 ('Uruguay', 2636)]

In [528]:
Counter(sim_results["second"]).most_common()[:5]

[('Brazil', 4840),
 ('Belgium', 3634),
 ('Peru', 3155),
 ('Portugal', 2975),
 ('France', 2827)]

In [529]:
Counter(sim_results["third"]).most_common()[:5]

[('Brazil', 7184),
 ('Belgium', 5335),
 ('Peru', 4546),
 ('Uruguay', 3518),
 ('Portugal', 3202)]

In [530]:
Counter(sim_results["fourth"]).most_common()[:5]

[('Brazil', 4840),
 ('Belgium', 3634),
 ('Peru', 3155),
 ('Portugal', 2975),
 ('France', 2827)]

* First: Brazil
* Second: Belgium
* Third: Peru
* Fourth: Portugal